# lecture 06: draw function:

- `line`
- `arrowed line`
- `draw rectangle`
- `draw circle`
- `put text`

In [7]:
import cv2 as cv 
import numpy as np 

In [8]:
img = cv.imread("data/lena.jpg",1)

print("shape height,width {}".format(img.shape))

# ------------------- Line -------------------
cv.line(img,(0,0),(250,250),(255,0,0),5,cv.LINE_4)

# ------------------- Arrowed Line -------------------
cv.arrowedLine(img,(0,255),(250,250),(255,0,0),5,cv.LINE_AA)

# ------------------- Rectangle  -------------------
"""

x1,y1____________________
|                        |
|                        |
|                        |
_____________________x2,y2

"""
cv.rectangle(img,(250,250),(450,450),(255,0,255),5)

# ------------------- Circle  -------------------
cv.circle(img,(350,350),100,(255,0,255),-1)

# ------------------- Put Text  -------------------
cv.putText(img,"OPENCV",(350,100),cv.FONT_HERSHEY_COMPLEX,1,(0,255,255),5)

cv.imshow('Show_Image',img)
if cv.waitKey(0) & 0xFF == ord('q'):
    cv.destroyAllWindows()

shape height,width (512, 512, 3)


---

<br>

There are 3 type of lines in openCV LINE_4 , LINE_8 and LINE_AA

- go to openCVThtorialsHindi then click basic.md and then go to lecture 12

<br>

---

# Create an image using numpy array:

In [11]:
# black image
black = np.zeros([512,512,3],np.uint8)
print(black)
cv.imshow("npIMG",black)
cv.waitKey(0)
cv.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [12]:
# white image
white = np.ones([512,512,3],np.uint8)
print(white)
cv.imshow("IMG",white)
cv.waitKey(0)
cv.destroyAllWindows()

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
